name: "Terraform CI/CD"
 
on:
 push:
   branches:
   - main
  #  paths:
  #  - terraform/**
 pull_request:
   branches:
   - main
  #  paths:
  #  - terraform/**

permissions:
      id-token: write
      contents: read

jobs:
 deploy-to-staging:
   name: "Terraform Staging Deployment"
   runs-on: ubuntu-latest
   environment: staging
   defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
       working-directory: ./terraform
 
   steps:
    - name: Checkout the repository to the runner
      uses: actions/checkout@v2
 
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{secrets.DEPLOY_ROLE}}
        aws-region: eu-west-2
        role-session-name: OIDCSession

    - name: Setup Terraform with specified version on the runner
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.7    
        terraform_wrapper: false
    
    - name: Terraform init
      run: terraform init -backend-config="bucket=${{ secrets.BUCKET_TF_STATE }}"
