### Workflow to deploy in development environment

name: "Terraform CI/CD"

on:
  push:
    branches:
      - main # your "trunk" branch
  # enables manual triggers
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  plan-dev:
    uses: ./.github/workflows/tf_plan.yml    
    with:
      path: terraform                  ## Path to terraform root module (Required)
      tf_version: 4.30.0                 ## Terraform version e.g: 1.1.0 Default=latest (Optional)
      tf_key: cromon-dev             ## Specifies name that will be given to terraform state file and plan artifact (Required)
      tf_vars_file: environments/dev.tfvars    ## Terraform TFVARS (Required)
      environment: dev
    secrets:
      aws_account: ${{ secrets.AWS_ACCOUNT }}
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      aws_region: ${{ secrets.AWS_REGION }}
      deploy_role: ${{ secrets.DEPLOY_ROLE }}
      
  deploy-dev:
    needs: plan-dev
    uses: ./.github/workflows/tf_apply.yml
    with:
      path: terraform                  ## Path to terraform root module (Required)
      tf_version: 4.30.0                 ## Terraform version e.g: 1.1.0 Default=latest (Optional)
      tf_key: cromon-dev             ## Specifies name that will be given to terraform state file and plan artifact (Required)
      tf_vars_file: environments/dev.tfvars    ## Terraform TFVARS (Required)
      environment: dev
    secrets:
      aws_account: ${{ secrets.AWS_ACCOUNT }}
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      aws_region: ${{ secrets.AWS_REGION }}
      deploy_role: ${{ secrets.DEPLOY_ROLE }}

  plan-prod:
    uses: ./.github/workflows/tf_plan.yml
    with:
      path: terraform                  ## Path to terraform root module (Required)
      tf_version: 4.30.0                 ## Terraform version e.g: 1.1.0 Default=latest (Optional)
      tf_key: cromon-prod             ## Specifies name that will be given to terraform state file and plan artifact (Required)
      tf_vars_file: environments/prod.tfvars    ## Terraform TFVARS (Required)
      environment: prod
    secrets:
      aws_account: ${{ secrets.AWS_ACCOUNT }}
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      aws_region: ${{ secrets.AWS_REGION }}
      deploy_role: ${{ secrets.DEPLOY_ROLE }}

  deploy-prod:
    needs: [plan-prod, deploy-dev]
    uses: ./.github/workflows/tf_apply.yml
    with:
      path: terraform                  ## Path to terraform root module (Required)
      tf_version: 4.30.0                 ## Terraform version e.g: 1.1.0 Default=latest (Optional)
      tf_key: cromon-prod          ## Specifies name that will be given to terraform state file and plan artifact (Required)
      tf_vars_file: environments/prod.tfvars    ## Terraform TFVARS (Required)
      environment: prod
    secrets:
      aws_account: ${{ secrets.AWS_ACCOUNT }}
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      aws_region: ${{ secrets.AWS_REGION }}
      deploy_role: ${{ secrets.DEPLOY_ROLE }}